version: '3'
services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    volumes:
      - ./minio:/data
      - ..env:/minio.env
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=$MINIOLOG
      - MINIO_ROOT_PASSWORD=$MINIOPASS
    ports:
      - "9000:9000"
      - "9001:9001"

  django_app:
    build:
      context: .
      dockerfile: Dockerfile_django
    container_name: django-app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
    - "8000:8000"


  my_utils:
    build:
      context: .
      dockerfile: Dockerfile_utils
    environment:
      - PYTHONUNBUFFERED=1
    container_name: my-utils
    depends_on:
      - minio
      - django_app


#env_file:
#      - .env
#    environment:
#      POSTGRES_USER: $POSTGRES_USER
#      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
#      POSTGRES_DB: $POSTGRES_DB