version: '3'
services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  django_app:
    build:
      context: .
      dockerfile: Dockerfile_django
    container_name: django-app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
    - "8000:8000"


  my_utils:
    build:
      context: .
      dockerfile: Dockerfile_utils
    environment:
      - PYTHONUNBUFFERED=1
    container_name: my-utils
    depends_on:
      - minio
      - django_app
